release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: trim21
    name: try

  target_commitish: '{{ .Commit }}'

  prerelease: auto

  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

